### ISSUE TITLE
Feat: Team Builder

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#1]
Implement a basic team builder that lets a user select 6 Pokemon with custom IVs, level (up to level 51), and moves.

### Requirements

- [x] Pokemon selection component #2 
- [x] Team Verifier #3 
- [x] Saving a team updates the value of `TeamContext`
- [x] A saved team is stored in a cookie which can update TeamContext on first render

### Notes

- The homepage needs a link to this team builder. The team builder should be on its own route in `/pages`.
- Styling will be a different issue, as there is no design mockup yet. The team builder will eventually be very similar to the Pokemon Showdown team builder.
- @jarthur22 has a lot of team builder code available to port over.

**Comment by ophidianab** [comment]
Should be up to level 51 to account for best-buddy with XL candy

**Comment by jarthur22** [comment]
👍

**Comment by DeveloperKhan** [comment]
this issue is a little too big for the deadline. i'm going to comment out the firebase features and use cookies for now. Firebase team/settings storage will be a separate issue for next milestone

**Comment by DeveloperKhan** [comment]
So the teambuilder is nearly done, but the pokemon selector (which is part of the teambuilder) is not yet complete. I'll close this issue but keep the pokemon selector part open. No PR yet
