### ISSUE TITLE
Feat: Analytics and Snapshota

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#115]
Use Firestore to store game snapshots
### Requirements

- [ ] Create a Firestore collection for game logs
- [ ] Store snapshots of a Room at each turn, countdown, and room join
- [ ] On room termination, upload the snapshot array to Firestore

**Comment by DeveloperKhan** [comment]
POG AWS
