### ISSUE TITLE
Feat: Add language localisation

### ISSUE THREAD

**Issue by theking465** [DeveloperKhan/pogo-web#175]
In order to better reach battlers, setup a translation workflow so the community can translate strings. 

- [x] Find a good translation platform
- [x] List all strings in a data file per language
- [x] Add a language selector in /settings
