### ISSUE TITLE
Feat: Profile Screen

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#182]
**NOTE: Requires designs from Design Team**
Implement the profile screen. Dependent on #60.

### Requirements

- [ ] Implement the stats component
- [ ] Update the user stats property on Firebase after every win/loss
- [ ] Implement a profile image + color selector
- [ ] Lock specific images/colors from being selected unless the profile has the correct flag in firebase
- [ ] Update the room browser with the profile image + color
- [ ] Add inputs to add external links: Silph Card, Discord, Twitter, YouTube, and Reddit

### Note
- The external link inputs should be built in a way so that the root URL cannot change, and thus you cannot post inappropriate links
