### ISSUE TITLE
Feat: Friends Widget

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#183]
**Note: Requires design by Design Team**
Implement the missing friends widget on the home page

### Requirements

- [x] Create a websocket connection on the homepage
- [x] Create a listener that listens for friend invites/battle requests and adds them to the "Friends Feed"
- [x] Create a feed to see which friends are online
- [x] Add an input to send friend requests
- [x] Add a button next to friends who are not in a battle to send battle request

### Notes
- The battle request should only let you join if you selected a team of the correct format
