### ISSUE TITLE
Feat: Buffering Inputs

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#45]
Record player inputs and queue actions in the backend

### Requirements

- [x] In `{frontend}/pages/game`, If an input is tapped while `currentMove !== null`, it should record the next input in a new state variable called `bufferedMove` AND send that input to the backend
- [x] If an input is tapped, `currentMove !== null`, and `bufferedMove !== null`, then the bufferedMove should only be overwritten if the new input has a higher rank (check notes)
- [x] In the `onAction` handler, if `player.current.action !== null`, then instead write the input into `player.current.bufferAction`
- [x] After the `{backend}/onTurn` handler resolves, if `player.current.action === null` then `player.current.action = player.current.bufferAction` and `player.current.bufferAction = null`
- [x] After the `{frontend}/onTurn` handler resolves, do the same thing with `currentMove` and `bufferedMove`

### Notes

- **Inputs have a rank they can be overwritten: Fast Move < Charge Move < Switch (strict inequalities!)**
- After you override a buffered input on the frontend, the new input should be sent to the backend and the backend should have logic to override the input
- Make sure to add logic to the backend that overwrites `player.current.bufferAction` if and only if a new action of higher rank is preregistered

**Comment by DeveloperKhan** [comment]
Almost done, but there are several visual glitches. Follow the progress on `feat/buffer-charge-moves`.

**Comment by DeveloperKhan** [comment]
Fixed most bugs, needs more testing tho
