### ISSUE TITLE
Feat: Firebase/Firestore

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#60]
Use Firestore to store and retrieve settings and teams.
### Requirements

- [ ] Implement a profile button that shows whether or not the user is currently a guest or a firebase authenticated user
- [ ] Implement a login/sign up UI that allows for Google auth and Email/Password auth
- [ ] If the user is authenticated, teams and settings should be pulled from firestore, else it should pull from local storage
- [ ] Implement the account page in the settings screen based on the Figma
- [ ] Keep the user logged in between sessions
