### ISSUE TITLE
Feat: Upgrade Homepage

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#61]
Redesign and implement the homepage.
### Requirements

- [ ] Section for logging in/out
- [ ] Section to host a game
- [ ] Section to browse and join a game
- [ ] Section to view/pick your team
### Notes
- We are removing the "Choose" feature from the teambuilder. Instead there will be a dropdown on the homepage, just like in Pokemon Showdown
- Hosting a game will now require you to specify a meta. You cannot join a game without a valid team for the meta.
- You can choose to host a "meta-less" game with no rulesets.

**Comment by DeveloperKhan** [comment]
Here's the design, I'll implement it if no one else takes it up in a few days
https://www.figma.com/file/YCYYmELqOfX2Wtw40DI4jN/Project-Grookey-Web-App?node-id=206%3A1
